#pragma once

#include <memory>

/*
Car class

Contains the physical and electrical model of the solar car, as well as all car
parameters and specific properties

Functions included:
  1. Energy required to drive a segment of the route
  2. Solar energy generated by the solar array
  3. Maximum battery capacity

Functions not included (handled by the simulator):
  1. Current time
  2. Location
  3. Battery state
  4. Driving/ charging the car
  5. Control-stop timings

*/
class Car {
 private:
  // Car parameters
  static constexpr double PASSIVE_POWER_W = 20.0;
  static constexpr double ROLLING_RESISTANCE = 0.0026;
  static constexpr double CDA = 0.15;
  static constexpr double ARRAY_EFFICIENCY = 0.252;
  static constexpr double MASS_KG = 283.0;
  static constexpr double BATTERY_EFFICIENCY = 0.98;
  static constexpr double MOTOR_EFFICIENCY = 0.80;
  static constexpr double ARRAY_AREA_M2 = 4.0;
  static constexpr double MAX_BATTERY_KWH = 5.2;

  // Assuming standard air density
  static constexpr double AIR_DENSITY_KG_M3 = 1.225;

 public:
  Car();

  // Energy required to travel a segment of the route
  double get_energy_consumption(double speed_kph, double distance_m,
                                double delta_altitude_m,
                                double time_seconds) const;

  // Solar power generated from DNI
  double get_solar_power(double dni) const;

  // Maximum battery capacity
  double get_battery_capacity() const;
};
